# Generated by Django 5.1.1 on 2024-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarryPotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harrypottercharacter',
            name='ancestry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='harrypottercharacter',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='harrypottercharacter',
            name='house',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='harrypottercharacter',
            name='patronus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='harrypottercharacter',
            name='yearOfBirth',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
